### ISSUE TITLE
Python 3.9无法安装

### ISSUE THREAD

**Issue by luoxhei** [I-love-study/graiax-silkcoder#5]
## 问题描述：
在 `Python3.9` 环境下安装本项目的模块会产生报错

## 环境：
+ Windows10
+ Python3.9
+ graiax-silkcoder==0.0.*

## 报错日志：
>   ERROR: Failed building wheel for graiax-silkcoder
Failed to build graiax-silkcoder
ERROR: Could not build wheels for graiax-silkcoder which use PEP 517 and cannot be installed directly

## 解决方案：
更换版本为 `Python3.8`

## 问题可能原因：
项目使用的 PEP517 与 Python3.9 版本之间产生难以预料的 bug
网上有过类似的记录 [pip install fails when using pep517](https://github.com/sqlalchemy/sqlalchemy/issues/5207)

**Comment by luoxhei** [comment]
> Same as #4

然而并不是，如果是的话并不会在3.8能安装但3.9不能安装的情况
>  error: command 'E:\\Microsoft VS 2019\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by I-love-study** [comment]
但是我现在就是3.9
然后我成功安装了silkcoder啊
请给出完整的报错信息

**Comment by luoxhei** [comment]
>  error: command 'E:\\Microsoft VS 2019\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  Traceback (most recent call last):
    File "e:\anaconda3\envs\lxh\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "e:\anaconda3\envs\lxh\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "e:\anaconda3\envs\lxh\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\luoxhei\AppData\Local\Temp\pip-build-env-xchha12i\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "C:\Users\luoxhei\AppData\Local\Temp\pip-build-env-xchha12i\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 72, in make_in
      wb.build()
    File "C:\Users\luoxhei\AppData\Local\Temp\pip-build-env-xchha12i\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 103, in build
      self._build(zip_file)
    File "C:\Users\luoxhei\AppData\Local\Temp\pip-build-env-xchha12i\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 135, in _build
      self._run_build_command(setup)
    File "C:\Users\luoxhei\AppData\Local\Temp\pip-build-env-xchha12i\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 163, in _run_build_command
      subprocess.check_call(
    File "e:\anaconda3\envs\lxh\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['e:/anaconda3/envs/lxh/python.exe', 'C:\\Users\\luoxhei\\AppData\\Local\\Temp\\pip-install-mqqjkcx1\\graiax-silkcoder_4f060ed9fc9b4ff898b830d99e3a67fb\\setup.py', 'build', '-b', 'C:\\Users\\luoxhei\\AppData\\Local\\Temp\\pip-install-mqqjkcx1\\graiax-silkcoder_4f060ed9fc9b4ff898b830d99e3a67fb\\build']' returned non-zero exit status 1.
  ERROR: Failed building wheel for graiax-silkcoder
Failed to build graiax-silkcoder
ERROR: Could not build wheels for graiax-silkcoder which use PEP 517 and cannot be installed directly

**Comment by luoxhei** [comment]
测试应该是我编译环境的个例，这个环境搭了挺久了，不知道为什么在 3.9 上出现该 bug

**Comment by BoBppy** [comment]
@I-love-study 

› Same as #4

这个不same吧，
我cp39也装不上去（
试了--no-use-pep517和--no-use-binary之类的也不行，报错与这个issue一致，不是c++的问题

**Comment by I-love-study** [comment]
> @I-love-study
> 
> › Same as #4
> 
> 这个不same吧，
> 我cp39也装不上去（
> 试了--no-use-pep517和--no-use-binary之类的也不行，报错与这个issue一致，不是c++的问题

哦我的上帝，能不能给一个完整的报错给我呢

**Comment by BoBppy** [comment]
@I-love-study 完整的log好像不太好抓
直接用›或者tee抓出来都不是完整的，我再试试看吧

**Comment by BoBppy** [comment]
[silk.log](https://github.com/I-love-study/graiax-silkcoder/files/6976580/silk.log)

完整的log @I-love-study

**Comment by I-love-study** [comment]
> [silk.log](https://github.com/I-love-study/graiax-silkcoder/files/6976580/silk.log)
> 
> 完整的log @I-love-study

我还是觉得跟 #4 的问题是一致的
`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`
我觉得肯定是哪里有地方做错了，你可以百度`error: Microsoft Visual C++ 14.0 or greater is required`看看怎么解决这个问题

未来可能通过github action为Windows的python3.8+提供whl

**Comment by BoBppy** [comment]
@I-love-study 
[ooo.log](https://github.com/I-love-study/graiax-silkcoder/files/6982052/ooo.log)
选择c艹桌面开发环境后取消勾选了Windows10SDK后再次尝试安装报的错误。
系统是8.1，愿whl早日出现🙏

**Comment by BoBppy** [comment]
@I-love-study 没看到有0.0.15，装上去了，谢谢
